### ISSUE TITLE
新增插件四个(生成百度搜索链接，获取{美女,风景,动漫}图片，获取诗词，代替主人反击插件)

### ISSUE THREAD

**Issue by hcr707305003** [nkxingxh/miraiez-plugins#3]
包名：
1. top.shiroi.baiduSearch 生成百度搜索链接
2. top.shiroi.moreImage 获取{美女,风景,动漫}图片
3. top.shiroi.poetry 获取诗词
4. top.shiroi.replaceMasterBeat 代替主人反击插件  (包含本地图片image目录)

**Comment by nkxingxh** [comment]
9c10e7f7134b985802d6978b85693595243db182
